# Generated by Django 4.1.5 on 2023-04-01 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("JIRA_CARD_DATA", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CardDataModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("num_cards", models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="CredsModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("api_token", models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(name="CardData",),
    ]
