# Generated by Django 4.1.5 on 2023-04-01 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("JIRA_CARD_DATA", "0002_carddatamodel_credsmodel_delete_carddata"),
    ]

    operations = [
        migrations.AddField(
            model_name="credsmodel",
            name="server",
            field=models.CharField(default=None, max_length=100),
        ),
    ]
