# Generated by Django 4.1.5 on 2023-04-01 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("JIRA_CARD_DATA", "0006_alter_credsmodel_server"),
    ]

    operations = [
        migrations.RemoveField(model_name="credsmodel", name="server",),
    ]
