# Generated by Django 4.1.5 on 2023-04-01 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("JIRA_CARD_DATA", "0007_remove_credsmodel_server"),
    ]

    operations = [
        migrations.AddField(
            model_name="credsmodel",
            name="server",
            field=models.CharField(default="", max_length=100, null=True),
        ),
    ]
