# Generated by Django 4.1.5 on 2023-03-22 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CardData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Issue_Type", models.CharField(max_length=20)),
                ("Project", models.CharField(max_length=20)),
                ("Time_Spent", models.CharField(max_length=20)),
                ("Status", models.CharField(max_length=20)),
                ("Story_Points", models.CharField(max_length=5)),
                ("Last_Viewed", models.CharField(max_length=20)),
                ("Sprint", models.CharField(max_length=20)),
                ("Priority", models.CharField(max_length=20)),
                ("Assignee", models.CharField(max_length=20)),
                ("Issue_Key", models.CharField(max_length=20)),
                ("Description", models.CharField(max_length=50)),
                ("Summary", models.TextField()),
                ("Reporter", models.CharField(max_length=20)),
            ],
        ),
    ]
